### PR TITLE
Fix the TOC when a local TOC is generated on a slide.

### PR DESCRIPTION
**Pull request by ptitmain**
Hi,
I corrected a bug when a TOC is inserted in a slide. The resulting code includes an additional backref link to handle the local TOC (this is due to the conversion from RST to HTML). Then, a TOC ref appears to be:

`<a href="...#slide:xx"> <a href="....#id:yy"> My title </a> </a>`

The #id link is generated by the rsttohtml converter and is useless in our case. The #slide:xx link is generated by generator.py. The link is then broken, because of the double link <a><a>.
I filtered the html output with a regex, as done for other useless html things. It works well.

### CODE REVIEW

**Comment by ionelmc** [comment]
This happens when you use the toc directive? Can you add an example in `examples/restructuredtext/slides.rst`?

**Comment by ptitmain** [comment]
Done !

**Comment by ptitmain** [comment]
Do you plan to merge ?

**Comment by ionelmc** [comment]
Yes, this weekend I'll do the merging/releasing.

**Comment by ionelmc** [comment]
Ok I've tried it now and I finally get what it does: it removes links from headings (that would appear if TOC is used). But then, shouldn't the links in the TOC have the correct `#slide:NN` value?

**Comment by ptitmain** [comment]
Yes, it would be better that the slide TOC links works (in the slide content). The TOC, on the left, have correct and working links.

For the links of the slide ocntent, as they are generated by the rst2pdf backend, there is no trivial way of getting the link. No ?

**Comment by ionelmc** [comment]
Anyway, I'm merging this part. Interested in making a fix for the link replacement? Basically all `<a class="internal" href="#stuff"` would get a replacement if `stuff` is one of those `toc-backref` anchors contain a `<hN id="stuff"`. It would be a change in parser.py ...

**Pull request merged**
